# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Skripsi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import pandas as pd
import numpy as np
from PandasModel import  PandasModel
from imblearn.over_sampling import SMOTE
from Modeling import RandomForest
from collections import Counter
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 694)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 1091, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 1091, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 100, 1101, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.OpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.OpenFile.setGeometry(QtCore.QRect(370, 130, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.OpenFile.setFont(font)
        self.OpenFile.setMouseTracking(True)
        self.OpenFile.setCheckable(False)
        self.OpenFile.setChecked(False)
        self.OpenFile.setAutoDefault(True)
        self.OpenFile.setDefault(False)
        self.OpenFile.setFlat(False)
        self.OpenFile.setObjectName("OpenFile")
        self.dir = QtWidgets.QLineEdit(self.centralwidget)
        self.dir.setGeometry(QtCore.QRect(10, 130, 341, 20))
        self.dir.setObjectName("dir")
        self.tableViewDataAwal = QtWidgets.QTableView(self.centralwidget)
        self.tableViewDataAwal.setGeometry(QtCore.QRect(10, 170, 641, 501))
        self.tableViewDataAwal.setObjectName("tableViewDataAwal")
        self.groupBoxPengujian = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxPengujian.setGeometry(QtCore.QRect(670, 120, 401, 251))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxPengujian.setFont(font)
        self.groupBoxPengujian.setFlat(False)
        self.groupBoxPengujian.setCheckable(False)
        self.groupBoxPengujian.setObjectName("groupBoxPengujian")
        self.label_3 = QtWidgets.QLabel(self.groupBoxPengujian)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBoxPengujian)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBoxPengujian)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.PushProses = QtWidgets.QPushButton(self.groupBoxPengujian)
        self.PushProses.setGeometry(QtCore.QRect(180, 210, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PushProses.setFont(font)
        self.PushProses.setObjectName("PushProses")
        self.PushBersihProses = QtWidgets.QPushButton(self.groupBoxPengujian)
        self.PushBersihProses.setGeometry(QtCore.QRect(280, 210, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PushBersihProses.setFont(font)
        self.PushBersihProses.setObjectName("PushBersihProses")
        self.lineEditFold = QtWidgets.QLineEdit(self.groupBoxPengujian)
        self.lineEditFold.setGeometry(QtCore.QRect(140, 100, 113, 20))
        self.lineEditFold.setObjectName("lineEditFold")
        self.lineEditTree = QtWidgets.QLineEdit(self.groupBoxPengujian)
        self.lineEditTree.setGeometry(QtCore.QRect(140, 150, 113, 20))
        self.lineEditTree.setObjectName("lineEditTree")
        self.RBYa = QtWidgets.QRadioButton(self.groupBoxPengujian)
        self.RBYa.setGeometry(QtCore.QRect(140, 50, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.RBYa.setFont(font)
        self.RBYa.setObjectName("RBYa")
        self.RBTIDAK = QtWidgets.QRadioButton(self.groupBoxPengujian)
        self.RBTIDAK.setGeometry(QtCore.QRect(190, 50, 61, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.RBTIDAK.setFont(font)
        self.RBTIDAK.setObjectName("RBTIDAK")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(670, 390, 401, 241))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 131, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 100, 131, 21))
        self.label_7.setObjectName("label_7")
        self.lineEditAkTrain = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditAkTrain.setGeometry(QtCore.QRect(20, 70, 113, 20))
        self.lineEditAkTrain.setObjectName("lineEditAkTrain")
        self.lineEditF1Train = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditF1Train.setGeometry(QtCore.QRect(20, 130, 113, 20))
        self.lineEditF1Train.setObjectName("lineEditF1Train")
        self.lineEditAkTest = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditAkTest.setGeometry(QtCore.QRect(240, 70, 113, 20))
        self.lineEditAkTest.setObjectName("lineEditAkTest")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(240, 40, 131, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(240, 100, 131, 21))
        self.label_9.setObjectName("label_9")
        self.lineEditF1Test = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditF1Test.setGeometry(QtCore.QRect(240, 130, 113, 20))
        self.lineEditF1Test.setObjectName("lineEditF1Test")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(20, 160, 131, 21))
        self.label_10.setObjectName("label_10")
        self.lineEditMAETrain = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditMAETrain.setGeometry(QtCore.QRect(20, 190, 113, 20))
        self.lineEditMAETrain.setObjectName("lineEditMAETrain")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(240, 160, 131, 21))
        self.label_11.setObjectName("label_11")
        self.lineEditMAETest = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditMAETest.setGeometry(QtCore.QRect(240, 190, 113, 20))
        self.lineEditMAETest.setObjectName("lineEditMAETest")
        self.pushButtonBersihkan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBersihkan.setGeometry(QtCore.QRect(460, 130, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButtonBersihkan.setFont(font)
        self.pushButtonBersihkan.setObjectName("pushButtonBersihkan")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(0, 80, 1091, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.OpenFile.clicked.connect(self.openFile)
        self.pushButtonBersihkan.clicked.connect(self.bersihkanTabelDataAwal)
        self.PushProses.clicked.connect(self.proses)
        self.PushBersihProses.clicked.connect(self.bersihkanProses)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def openFile(self):
            global dataset, filename
            filename, _ = QtWidgets.QFileDialog.getOpenFileName()
            dataset = pd.read_csv(filename)
            df = PandasModel(dataset)
            self.dir.setText(filename)
            self.tableViewDataAwal.setModel(df)


    def bersihkanTabelDataAwal(self):
            df = PandasModel()
            self.tableViewDataAwal.setModel(df)
            self.dir.clear()



    def proses(self):
        if self.dir.text() != "" :
            X = dataset.drop(['icu'], axis=1).values
            y = dataset['icu'].values
            counter1 = Counter(y)
            print("Data Sebelum Balancing:", counter1)

            try:

                Kf = int(self.lineEditFold.text())
                tree = int(self.lineEditTree.text())

                if self.RBYa.isChecked():
                        sm = SMOTE(random_state=42)
                        X_res, y_res = sm.fit_resample(X, y)
                        counter = Counter(y_res)
                        print("Data Setelah Balancing:",counter)
                        rdf = RandomForest(X_res,y_res,Kf,tree)
                        self.accuracy_rdf_train, self.accuracy_rdf_test, self.f1Score_rdf_train, self.f1Score_rdf_test = rdf.get_result()

                elif self.RBTIDAK.isChecked():
                        rdf = RandomForest(X, y, Kf, tree)
                        self.accuracy_rdf_train, self.accuracy_rdf_test, self.f1Score_rdf_train, self.f1Score_rdf_test  = rdf.get_result()

                self.lineEditAkTrain.setText("{:.3f}".format(np.mean(self.accuracy_rdf_train)))
                self.lineEditF1Train.setText("{:.3f}".format(np.mean(self.f1Score_rdf_train)))
                #self.lineEditMAETrain.setText("{:.3f}".format(np.mean(self.MAE_rdf_train)))

                self.lineEditAkTest.setText("{:.3f}".format(np.mean(self.accuracy_rdf_test)))
                self.lineEditF1Test.setText("{:.3f}".format(np.mean(self.f1Score_rdf_test)))
                #self.lineEditMAETest.setText("{:.3f}".format(np.mean(self.MAE_rdf_test)))

            except Exception as e :
                errBox = QMessageBox()
                errBox.setWindowTitle('Error')
                errBox.setText('Error: ' + 'Terjadi Kesalahan Silahkan Cek Kembali!!!')
                errBox.addButton(QMessageBox.Ok)
                errBox.exec()

    def bersihkanProses(self):
        self.lineEditTree.clear()
        self.lineEditFold.clear()
        self.lineEditF1Test.clear()
        self.lineEditAkTest.clear()
        self.lineEditAkTrain.clear()
        self.lineEditF1Train.clear()
        self.lineEditMAETest.clear()
        self.lineEditMAETrain.clear()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Klasifikasi Pasien Covid-19 yang Membutuhkan ICU Menggunakan Random Forest"))
        self.label_2.setText(_translate("MainWindow", "I Gusti Ngurah Astika Pradnyana Dalem"))
        self.OpenFile.setText(_translate("MainWindow", "Cari File"))
        self.groupBoxPengujian.setTitle(_translate("MainWindow", "Pengujian"))
        self.label_3.setText(_translate("MainWindow", "Balancing :"))
        self.label_4.setText(_translate("MainWindow", "K- Fold    :"))
        self.label_5.setText(_translate("MainWindow", "Jumlah Tree :"))
        self.PushProses.setText(_translate("MainWindow", "Proses"))
        self.PushBersihProses.setText(_translate("MainWindow", "Bersihkan"))
        self.RBYa.setText(_translate("MainWindow", "Ya"))
        self.RBTIDAK.setText(_translate("MainWindow", "Tidak"))
        self.groupBox.setTitle(_translate("MainWindow", "Hasil Pengujian"))
        self.label_6.setText(_translate("MainWindow", "Akurasi Training"))
        self.label_7.setText(_translate("MainWindow", "F1 Score Training"))
        self.label_8.setText(_translate("MainWindow", "Akurasi Testing"))
        self.label_9.setText(_translate("MainWindow", "F1-Score Testing"))
        self.label_10.setText(_translate("MainWindow", "MAE Training"))
        self.label_11.setText(_translate("MainWindow", "MAE Testing"))
        self.pushButtonBersihkan.setText(_translate("MainWindow", "Bersihkan"))
        self.label_12.setText(_translate("MainWindow", "185314136"))

if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())